-- Supabase ダッシュボードの SQL Editor で実行してください
create table if not exists analyses (
  id bigint generated by default as identity primary key,
  url text not null,
  title text,
  replies jsonb not null default '[]',
  created_at timestamptz default now()
);

-- 匿名アクセスで挿入・参照を許可（RLS が有効な場合はポリシー設定が必要です）
alter table analyses enable row level security;

create policy "Allow anonymous insert" on analyses for insert to anon with check (true);
create policy "Allow anonymous select" on analyses for select to anon using (true);

-- User feedback (web UI → /api/feedback)
create table if not exists feedback (
  id bigint generated by default as identity primary key,
  url text not null default '',
  title text,
  rating text not null,
  comment text,
  created_at timestamptz default now()
);

alter table feedback enable row level security;

create policy "Allow anonymous insert feedback" on feedback for insert to anon with check (true);
-- Optional: allow reading your own feedback in admin; app does not select from client
create policy "Allow anonymous select feedback" on feedback for select to anon using (true);
