-- Supabase ダッシュボードの SQL Editor で実行してください
create table if not exists analyses (
  id bigint generated by default as identity primary key,
  url text not null,
  title text,
  replies jsonb not null default '[]',
  created_at timestamptz default now()
);

-- 匿名アクセスで挿入・参照を許可（RLS が有効な場合はポリシー設定が必要です）
alter table analyses enable row level security;

create policy "Allow anonymous insert" on analyses for insert to anon with check (true);
create policy "Allow anonymous select" on analyses for select to anon using (true);
